# This is the remark configration for testing deployments
# (i.e. .github/workflows/test-deploy.yml)

plugins:
- remark-validate-links
- - remark-lint-no-dead-urls
  - skipUrlPatterns:
    - https://rancher.rd.localhost
    - https://openai.com/api/
    - https://docs.openwebui.com/
    - https://openwebui.com/
    skipLocalhost: true
