name: Test deployment

on:
  pull_request:
    branches: [main]

permissions: {}

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Check links
        run: >-
          yarn run remark
          --rc-path .remarkrc.yaml
          --frail
          ./docs/
          ./versioned_docs/
      - name: Test build
        run: yarn build
